// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/account/me': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/account/me.get').default>>>>
    }
    '/api/addresses/search': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/addresses/search.get').default>>>>
    }
    '/api/alerts/gpon-rx': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/alerts/gpon-rx.get').default>>>>
    }
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/auth/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/logout.post').default>>>>
    }
    '/api/auth/session': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/session.get').default>>>>
    }
    '/api/automation/scripts/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/automation/scripts/[id].delete').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/automation/scripts/[id].patch').default>>>>
    }
    '/api/automation/scripts/:id/render': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/automation/scripts/[id]/render.post').default>>>>
    }
    '/api/automation/scripts/:id/run': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/automation/scripts/[id]/run.post').default>>>>
    }
    '/api/automation/scripts': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/automation/scripts/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/automation/scripts/index.post').default>>>>
    }
    '/api/automation/variables/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/automation/variables/[id].delete').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/automation/variables/[id].patch').default>>>>
    }
    '/api/automation/variables': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/automation/variables/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/automation/variables/index.post').default>>>>
    }
    '/api/automation/variables/sources': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/automation/variables/sources.get').default>>>>
    }
    '/api/billing/assignments/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/billing/assignments/[id].delete').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/billing/assignments/[id].patch').default>>>>
    }
    '/api/billing/assignments': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/billing/assignments/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/billing/assignments/index.post').default>>>>
    }
    '/api/billing/subscriptions/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/billing/subscriptions/[id].delete').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/billing/subscriptions/[id].patch').default>>>>
    }
    '/api/billing/subscriptions': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/billing/subscriptions/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/billing/subscriptions/index.post').default>>>>
    }
    '/api/billing/tariffs/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/billing/tariffs/[id].delete').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/billing/tariffs/[id].patch').default>>>>
    }
    '/api/billing/tariffs': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/billing/tariffs/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/billing/tariffs/index.post').default>>>>
    }
    '/api/crm/customer-devices/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/crm/customer-devices/[id].delete').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/crm/customer-devices/[id].patch').default>>>>
    }
    '/api/crm/customer-devices': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/crm/customer-devices/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/crm/customer-devices/index.post').default>>>>
    }
    '/api/crm/customers/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/crm/customers/[id].delete').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/crm/customers/[id].patch').default>>>>
    }
    '/api/crm/customers': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/crm/customers/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/crm/customers/index.post').default>>>>
    }
    '/api/crm/services/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/crm/services/[id].delete').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/crm/services/[id].patch').default>>>>
    }
    '/api/crm/services': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/crm/services/index.post').default>>>>
    }
    '/api/customers': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/customers').default>>>>
    }
    '/api/dashboard/summary': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dashboard/summary.get').default>>>>
    }
    '/api/diagnostics/customer-devices/:id/check': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/diagnostics/customer-devices/[id]/check.post').default>>>>
    }
    '/api/diagnostics/customer-devices/:id/olt-lookup': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/diagnostics/customer-devices/[id]/olt-lookup.post').default>>>>
    }
    '/api/diagnostics/customer-devices/:id/sync-lease': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/diagnostics/customer-devices/[id]/sync-lease.post').default>>>>
    }
    '/api/diagnostics/equipment/:id/command-tree': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/diagnostics/equipment/[id]/command-tree.post').default>>>>
    }
    '/api/diagnostics/equipment/:id/dhcp-leases': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/diagnostics/equipment/[id]/dhcp-leases.get').default>>>>
    }
    '/api/diagnostics/equipment/:id/mac-check': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/diagnostics/equipment/[id]/mac-check.post').default>>>>
    }
    '/api/diagnostics/equipment/:id/mikrotik-check': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/diagnostics/equipment/[id]/mikrotik-check.post').default>>>>
    }
    '/api/diagnostics/equipment/:id/netflow-config': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/diagnostics/equipment/[id]/netflow-config.post').default>>>>
    }
    '/api/diagnostics/equipment/:id/onu-ip-host': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/diagnostics/equipment/[id]/onu-ip-host.post').default>>>>
    }
    '/api/diagnostics/runs/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/diagnostics/runs/[id].delete').default>>>>
    }
    '/api/ftth/imports/dasan/:equipmentId/ip-hosts': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ftth/imports/dasan/[equipmentId]/ip-hosts.post').default>>>>
    }
    '/api/ftth/imports/dasan/:equipmentId/jobs': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ftth/imports/dasan/[equipmentId]/jobs.post').default>>>>
    }
    '/api/ftth/imports/dasan/:equipmentId/mac-map': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ftth/imports/dasan/[equipmentId]/mac-map.post').default>>>>
    }
    '/api/ftth/imports/dasan/:equipmentId/onus': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ftth/imports/dasan/[equipmentId]/onus.post').default>>>>
    }
    '/api/ftth/imports/jobs/:jobId': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ftth/imports/jobs/[jobId].get').default>>>>
    }
    '/api/ftth/imports/options': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ftth/imports/options.get').default>>>>
    }
    '/api/ftth/mac-map': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ftth/mac-map/index.get').default>>>>
    }
    '/api/ftth/olts': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ftth/olts/index.get').default>>>>
    }
    '/api/ftth/onuses/:id/link-customer': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ftth/onuses/[id]/link-customer.post').default>>>>
    }
    '/api/ftth/onuses/:id/link-equipment': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ftth/onuses/[id]/link-equipment.post').default>>>>
    }
    '/api/ftth/onuses': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ftth/onuses/index.get').default>>>>
    }
    '/api/ftth/pons': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ftth/pons/index.get').default>>>>
    }
    '/api/ftth/transparent-links': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ftth/transparent-links/index.get').default>>>>
    }
    '/api/import/dasan/:equipmentId/mac-map': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/import/dasan/[equipmentId]/mac-map.post').default>>>>
    }
    '/api/import/dasan/:equipmentId/onus': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/import/dasan/[equipmentId]/onus.post').default>>>>
    }
    '/api/import/mikrotik/:equipmentId/config': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/import/mikrotik/[equipmentId]/config.post').default>>>>
    }
    '/api/import/mikrotik/:equipmentId/leases': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/import/mikrotik/[equipmentId]/leases.post').default>>>>
    }
    '/api/import/mikrotik/:equipmentId/networks': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/import/mikrotik/[equipmentId]/networks.post').default>>>>
    }
    '/api/import/runs/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/import/runs/[id].delete').default>>>>
    }
    '/api/mails': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/mails').default>>>>
    }
    '/api/members': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/members').default>>>>
    }
    '/api/netflow/flows': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/netflow/flows.get').default>>>>
    }
    '/api/netflow/ingest-aggregate': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/netflow/ingest-aggregate.post').default>>>>
    }
    '/api/network/access-profile-bindings': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/network/access-profile-bindings/index.post').default>>>>
    }
    '/api/network/access-profiles/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/network/access-profiles/[id].delete').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/network/access-profiles/[id].patch').default>>>>
    }
    '/api/network/access-profiles': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/network/access-profiles/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/network/access-profiles/index.post').default>>>>
    }
    '/api/network/equipment/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/network/equipment/[id].delete').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/network/equipment/[id].patch').default>>>>
    }
    '/api/network/equipment': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/network/equipment/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/network/equipment/index.post').default>>>>
    }
    '/api/network/import-options': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/network/import-options.get').default>>>>
    }
    '/api/network/lines/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/network/lines/[id].delete').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/network/lines/[id].patch').default>>>>
    }
    '/api/network/lines': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/network/lines/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/network/lines/index.post').default>>>>
    }
    '/api/network/nodes/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/network/nodes/[id].delete').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/network/nodes/[id].patch').default>>>>
    }
    '/api/network/nodes': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/network/nodes/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/network/nodes/index.post').default>>>>
    }
    '/api/notifications': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/notifications').default>>>>
    }
    '/api/pit/export': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/pit/export.get').default>>>>
    }
    '/api/pit/validation': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/pit/validation.get').default>>>>
    }
    '/api/search': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/search.get').default>>>>
    }
    '/api/system/dictionaries': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/system/dictionaries.get').default>>>>
    }
    '/api/system/dictionaries/import': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/system/dictionaries/import.post').default>>>>
    }
    '/api/system/options': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/system/options.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+nitro-server@4.4.5_@babel+core@7.29.0_db0@0.3.4_drizzle-orm@0.45.2_@opentelemetry_3474243ea9be90cd80c921245ccbee2e/node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+icon@2.2.1_magicast@0.5.2_vite@7.3.2_@types+node@25.9.1_jiti@2.6.1_lightningcss@1_adf77149c6e3dbdacd26b6c891b63df6/node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}